######################################################################
# environment and task
env_name: transport

# future action forecasts
action_dim: 14
horizon_steps: 8
act_steps: 8

# observation history
obs_dim: 18  # proprioception only
cond_steps: 1
img_cond_steps: 1

# observation shape
shape_meta:
  obs:
    rgb:
      shape: [6, 96, 96]  # not counting img_cond_steps
    state:
      shape: [18]
  action:
    shape: [14]
###################################################################


defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.eval.eval_meanflow_img_agent.EvalImgMeanFlowAgent

name: ${env_name}_eval_meanflow_mlp_img_ta${horizon_steps}
logdir: 
  ${oc.env:REINFLOW_LOG_DIR}/robomimic/eval/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path:
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}-img.json
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/robomimic/${env_name}-img/normalization.npz

load_ema: true
seed: 42
device: cuda:0
sim_device:
n_steps: 200  # each episode takes max_episode_steps / act_steps steps
render_num: 0
batch_size: 128
denoising_step_list: [5]

env:
  n_envs: 50
  name: ${env_name}
  best_reward_threshold_for_success: 1
  max_episode_steps: 800
  save_video: false
  use_image_obs: true
  wrappers:
    robomimic_image:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos', "robot1_eef_pos",
        "robot1_eef_quat", "robot1_gripper_qpos"]
      image_keys: ['shouldercamera0_image', 'shouldercamera1_image']
      shape_meta: ${shape_meta}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true
  render: true

model:
  _target_: model.flow.meanflow.MeanFlow
  network:
    _target_: model.flow.mlp_meanflow.MeanFlowViT
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'6 * ${img_cond_steps}'} # each image patch is history concatenated
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    img_cond_steps: ${img_cond_steps}
    time_dim: 16
    r_embedding_dim: 16
    mlp_dims: [512, 512, 512]
    activation_type: "Mish"
    out_activation_type: "Identity"
    use_layernorm: false
    residual_style: true
    spatial_emb: 128
    visual_feature_dim: 128
    dropout: 0.1
    num_img: 2
    augment: true
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  max_denoising_steps: 5
  seed: ${seed}
  flow_ratio: 0.5
  gamma: 0.5
  c: 1e-3
  sample_t_type: uniform
  use_adaptive_loss: false
