######################################################################
# environment and task
env_suite: robomimic
env: lift

# future action forecasts
action_dim: 7
horizon_steps: 4

# observation history
obs_dim: 9  # proprioception only
cond_steps: 1
img_cond_steps: 1

# String version for file naming
dispersive_weight_name: "0p5"     # corresponds to dispersive_loss_weight: 0.5
dispersive_temp_name: "0p5"       # corresponds to dispersive_temperature: 0.5
dispersive_type_name: "infnce"    # corresponds to dispersive_loss_type: "infonce_l2"

# observation shape
shape_meta:
  obs:
    rgb:
      shape: [3, 96, 96]  # not counting img_cond_steps
    state:
      shape: [9]
  action: 
    shape: [7]
###################################################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_shortcut_dispersive_agent.TrainMeanFlowDispersiveAgent
name: ${env}_pre_meanflow_dispersive_mlp_img_ta${horizon_steps}_${dispersive_type_name}_d${dispersive_weight_name}_t${dispersive_temp_name}
logdir: ${oc.env:REINFLOW_LOG_DIR}/robomimic/pretrain/${env}/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:REINFLOW_DATA_DIR}/robomimic/${env}-img/train.npz

# MeanFlow parameters
flow_ratio: 0.5  # ratio of samples using flow consistency (r=t)
gamma: 0.5       # parameter for adaptive L2 loss
c: 1e-3          # stability constant for adaptive loss

batch_size: 256
seed: 42
device: cuda:0
test_in_mujoco: false
max_n_episodes: -1
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}  # Use environment variable
  project: DM1-robomimic-${env}-pretrain  # ReinFlow project identifier
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}_meanflow_dispersive  # Add meanflow_dispersive identifier to run name
  offline_mode: false

train:
  n_epochs: 2000
  batch_size: ${batch_size}
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 2000
    warmup_steps: 100
    min_lr: 1e-5
  epoch_start_ema: 20
  update_ema_freq: 10
  save_model_freq: 100
  log_freq: 25

model:
  _target_: model.flow.shortcut_dispersive.MeanFlowDispersive
  network:
    _target_: model.flow.mlp_meanflow.MeanFlowViT
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'${shape_meta.obs.rgb.shape[0]} * ${img_cond_steps}'} # each image patch is history concatenated
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    img_cond_steps: ${img_cond_steps}
    time_dim: 16
    r_embedding_dim: 16
    mlp_dims: [768, 768, 768]
    activation_type: Mish
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
    spatial_emb: 128
    visual_feature_dim: 128
    dropout: 0.1
    num_img: 1
    augment: true
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1 
  obs_dim: ${obs_dim}
  max_denoising_steps: 5  # MeanFlow designed for 1-step generation
  seed: ${seed}
  flow_ratio: ${flow_ratio}
  gamma: ${gamma}
  c: ${c}
  sample_t_type: lognormal
  use_adaptive_loss: false
  # Dispersive Loss parameters
  dispersive_loss_weight: 0.5        # Weight coefficient for dispersive loss
  dispersive_loss_type: "infonce_l2"  # Type: infonce_l2, infonce_cosine, hinge, covariance
  dispersive_temperature: 0.5        # Temperature for InfoNCE variants (optimal from paper)
  dispersive_margin: 1.0             # Margin for hinge loss
  apply_dispersive_to_embeddings: true   # Apply to embeddings (time, r, condition)

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  use_img: true
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  max_n_episodes: ${max_n_episodes}
  cond_steps: ${cond_steps}
  img_cond_steps: ${img_cond_steps}
  device: ${device}